name: CI

on: [push]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        uses: php-actions/composer@v5

      - name: Execute tests
        run: bin/phpunit
